### ISSUE TITLE
Registering from a razor page

### ISSUE THREAD

**Issue by hammie1010** [nenoNaninu/TypedSignalR.Client#110]
From a Blazor Razor page, when registering the client interface: 

`var subscription = hubConnection.Register<IDatafeedClient>(this);`

This exception is thrown:

System.InvalidOperationException: Failed to register a receiver. TypedSignalR.Client did not generate source code to register a receiver, which type is Trading.Abstractions.Datafeed.IDatafeedClient.
   at TypedSignalR.Client.HubConnectionExtensions.Register[TReceiver](HubConnection connection, TReceiver receiver) in \TypedSignalR.Client\TypedSignalR.Client.SourceGenerator\TypedSignalR.Client.HubConnectionExtensions.Generated.cs:line 38
   at Trading.IntlWeb.Pages.SignalRClientTest.OnInitializedAsync() in \Trading.IntlWeb\Pages\SignalRClientTest.razor:line 30
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<WaitForQuiescence>g__ProcessAsynchronousWork|48_0()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.WaitForQuiescence()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderRootComponentAsync(Int32 componentId, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.HtmlRenderer.RenderComponentAsync(Type componentType, ParameterView initialParameters)
   at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c__11`1.<<InvokeAsync>b__11_0>d.MoveNext()

Why would this occur?

**Comment by hammie1010** [comment]
I think the issue is if you implement this directly in the razor file, it won't work, but if you put it in a code behind partial class it'll work.

**Comment by nenoNaninu** [comment]
A razor file (`.razor`) is not a standard C# file (`.cs`). Razor files are compiled by the razor compiler. The C# Source Generator then analyzes the C# code the user wrote and generates the code. If the razor compiler outputs C# code and the C# Source Generator can analyze that output, then CreateHubProxy and Register in `TypedSignalR.Client` would work correctly.
However, the reality is different.
Is the razor compiler executed before the C# Source Generator? or even if the razor compiler is executed before, can the C# Source Generator analyze the output? Also, that output may not be C#. Therefore, it is difficult for the C# Source Generator to analyze the code in the `@code` block of a razor file and generate code.

And `TypedSignalR.Client` is a C# Source Generator.
Therefore, calling `CreateHubProxy` or `Register` directly in the `@code` block will not generate the code correctly.
As you know, this problem can be solved by using `CreateHubProxy` or `Register` in a regular C# file (e.g., code behind).
